### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by guoyansi** [az8321550/express-velocity-front-end#1]
hello,哥们,你的node是什么版本的.这个项目很棒啊 .

**Comment by bodyno** [comment]
@guoyansi v0.12.4

**Comment by bodyno** [comment]
@guoyansi 如果喜欢 可以点一下star并follow一下本人

**Comment by guoyansi** [comment]
你却定这是前后台分离吗?我感觉不像,你都使用了render了.你这是在控制前端的页面跳转了.
你使用了好多前端技术,但是感觉没有做到彻底的前后台分离啊

**Comment by bodyno** [comment]
@guoyansi 已经前后端分离了，不需要依赖后端环境就可以开发了

难道说你理解的前后端分离是全部用静态页面？

模板引擎的好处是有很多的:smile:

**Comment by guoyansi** [comment]
可以加你扣扣,请教一下你关于前后端分离的问题吗?

**Comment by bodyno** [comment]
@guoyansi 3292286841
