### ISSUE TITLE
grunt build过程报错

### ISSUE THREAD

**Issue by lileichinasoft** [az8321550/express-velocity-front-end#3]
> grunt build

express-velocity-front-end/node_modules/node-sass/vendor/linux-x64-11/binding.node: ELF load command past end of file
Warning: Task "sass:build" not found. Use --force to continue.

**Comment by lileichinasoft** [comment]
> > Local Npm module "grunt-sass" not found. Is it installed?

**Comment by lileichinasoft** [comment]
➜  express-velocity-front-end git:(master) ✗ node -v
v0.10.24
➜  express-velocity-front-end git:(master) ✗ npm -v
3.5.0

**Comment by bodyno** [comment]
可以把node-sass 装在全局中
`
npm install node-sass -g
`
